### ISSUE TITLE
coreinfrastructure.org/grants died

### ISSUE THREAD

**Issue by matkoniecz** [renewablefreedom/funding-sources#10]
> Core Infrastructure Initiative,"""The Core Infrastructure Initiative (CII) and its members have come together to invest in core infrastructure, providing funding for fundamental projects like OpenSSL, OpenSSH, NTPd and others.""","<a href=""https://www.coreinfrastructure.org/grants"">https://www.coreinfrastructure.org/grants</a>"

Not sure is https://www.coreinfrastructure.org/programs/ is an useful replacement (also, is this project maintained?)

**Comment by moba** [comment]
I think CII has restructured their programs and stopped providing grants via open applications, so probably it is better to remove it.
