### ISSUE TITLE
csr.cisco.com is dead

### ISSUE THREAD

**Issue by matkoniecz** [renewablefreedom/funding-sources#11]
> Cisco Foundation,"""Cisco and the Cisco Foundation provide cash, products, and people to support organizations with scalable, replicable, and sustainable solutions that use Internet and network technology to benefit individuals and communities around the world. Cisco social investments reduce hunger, increase access to education and technology, empower people living in poverty to get jobs and start their own businesses, and restore critical services for disaster victims.""","<a href=""http://csr.cisco.com/pages/support-for-nonprofits"">http://csr.cisco.com/pages/support-for-nonprofits</a>"

not looked is it fully gone or just moved

**Comment by moba** [comment]
looks like it moved to https://www.cisco.com/c/en/us/about/csr/community/nonprofits.html
