### ISSUE TITLE
Use comma as field delimiter

### ISSUE THREAD

**Issue by sebkur** [renewablefreedom/funding-sources#7]
I suggest using comma as a field delimiter, so that GitHub displays the CSV data nicely.
Compare [sebkur/funding-2.0/data/funding-sources.csv](https://github.com/sebkur/funding-2.0/blob/master/data/funding-sources.csv) to [renewablefreedom/funding-sources/rff-funding-sources.csv](https://github.com/renewablefreedom/funding-sources/blob/master/rff-funding-sources.csv) to see what I mean.

I assume this change requires a minimal change in your website setup, but whatever your infrastructure, it should be possible. I can offer to reformat the CSV as a PR if that helps.

**Comment by moba** [comment]
Good suggestion. I will test this with Tablepress later this week (which is what we're using at the moment).

**Comment by moba** [comment]
I finally got around to testing it, and as expected Tablepress has no problem importing comma-separated values. :)
